import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("logs", "./routes/logs.jsx", [
    route("overview", "./routes/overview.jsx"),
    route("bottles", "./routes/allBottles.jsx"),
    route("foods", "./routes/allFoods.jsx"),
    route("naps", "./routes/allNaps.jsx"),
    route("poops", "./routes/allPoops.jsx"),
    route("temperature", "./routes/allTemps.jsx"),
    route("medication", "./routes/allMeds.jsx"),
  ]),
  route("add-logger", "./routes/addLoggerAction.jsx"),
  route("delete-logger", "./routes/deleteLoggerAction.jsx"),
  route("bottle-logger", "./routes/bottleLoggerAction.jsx"),
  route("food-logger", "./routes/foodLoggerAction.jsx"),
  route("nap-logger", "./routes/napLoggerAction.jsx"),
  route("poop-logger", "./routes/poopLoggerAction.jsx"),
  route("temp-logger", "./routes/tempLoggerAction.jsx"),
  route("med-logger", "./routes/medLoggerAction.jsx"),
  route("breastleft-logger", "./routes/breastLeftLoggerAction.jsx"),
  route("breastright-logger", "./routes/breastRightLoggerAction.jsx"),
  route("select-todayview", "./routes/selectTodayViewAction.jsx"),
  route("select-allview", "./routes/selectAllViewAction.jsx"),
  route("edit-bottle", "./routes/editBottleAction.jsx"),
  route("delete-log", "./routes/deleteLogAction.jsx"),
  route("edit-food", "./routes/editFoodAction.jsx"),
  route("edit-nap", "./routes/editNapAction.jsx"),
  route("edit-poop", "./routes/editPoopAction.jsx"),
  route("edit-temp", "./routes/editTempAction.jsx"),
  route("edit-med", "./routes/editMedAction.jsx"),
  route("set-timezone", "./routes/setTimezoneAction.jsx"),
] satisfies RouteConfig;
